version: '3'

services:
  holidapp:
    env_file:
      - .env-dev
    build:
      context: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    image: a5308y/holidapp
    volumes:
      - .:/app
  db:
    env_file:
      - .env-dev
    image: postgres:9.6
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/dev_data
volumes:
  pgdata:
