version: '3'

# Containers we are going to run
services:
  phoenix:
    build:
      # Here we define that it should build from the current directory
      context: .
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      - db
  db:
    # We use the predefined Postgres image
    image: postgres:9.6
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata:
