version: '3'

services:
  holidapp:
    env_file:
      - .env-prod
    build:
      context: .
    ports:
      - "80:4000"
    depends_on:
      - db
    image: a5308y/holidapp
    restart: always
  db:
    env_file:
      - .env-prod
    image: postgres:9.6
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
